
server.port=8080
spring.application.name=loja_roupas



# Conexão com o Banco
spring.datasource.url=jdbc:mysql://localhost:3306/loja_roupas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rafa

# Configurações do Hibernate (JPA)
# 'update' faz o Java criar a tabela se ela não existir ou atualizar se você mudar o código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true